### ISSUE TITLE
Does this work under iOS8?

### ISSUE THREAD

**Issue by dsjoerg** [Shmoopi/iOS-System-Services#12]
Thank you :)

**Comment by Shmoopi** [comment]
Hello dsjoerg,

Great question!

As far as the class building and working on iOS 8, yes, it works and does not cause any crashes (that we're aware of).  Most methods are wrapped in try-catch blocks to prevent any unexpected exceptions.

As far as every aspect of the library is concerned, no, not all methods work entirely as anticipated.  There are a few methods that may not return valid or expected output.  For example, the Wi-Fi MAC Address method will not return a valid MAC Address on iOS 7+ because the feature was disabled due to advertiser abuse.  Likewise, the Cellular MAC Address will not return a valid MAC Address on iOS 7+ for the same reason.  Other methods like the UUID method relied on a valid MAC address and will no longer come up with a unique identifier with which to use.  On the other hand, some methods have always been a little difficult to work with, including the processor speed, which is not always valid when queried.  These methods will likely be deprecated in a future update to this library, but still work on older versions of iOS.

I hope that answers your question!

Thanks,
Shmoopi LLC
