### ISSUE TITLE
build failed on iOS9.2

### ISSUE THREAD

**Issue by CodingGou** [Shmoopi/iOS-System-Services#22]
when I drag the file named System Services into my project instead of pod it,it build failed,it tells that UIInterfaceOrientation is not the expected type,and with many errors ,but the demo runs well, little confused.Can you tell me why? Maybe I should use the pod?

**Comment by CodingGou** [comment]
![image](https://cloud.githubusercontent.com/assets/14820712/11972730/59766c70-a98b-11e5-94e8-58f4af93e81a.png)

**Comment by CodingGou** [comment]
i have try it with pod,it works well ,why it couldn't use the source files?

**Comment by Shmoopi** [comment]
Hi @CodingGou,

That's a great question!  It appears that the demo project and Cocoa Pod implementation both have a pre-compiled header (.pch) file that includes a UIKit import.  We've updated the project to include the UIKit imports into the necessary classes so that the .pch file is no longer necessary to include the class without using Cocoa Pods.  Sorry for the confusion.

Thanks,
Shmoopi

**Comment by CodingGou** [comment]
Thank for you reply! it works well,but it still has  litter flow ,like the following picture
the systemCheck method is deprecated
If you can solve it !That's will be a very nice job!

**Comment by Shmoopi** [comment]
@CodingGou,

Not a problem.  We've kept the 'system' call in the latest release but deprecated its usage.  You will get a warning because of it, but it shouldn't cause any issues.  We are planning on removing it at a later date.

Thanks,
Shmoopi
