### ISSUE TITLE
iOS 10.2 Issue

### ISSUE THREAD

**Issue by iremkorkmaz** [Shmoopi/iOS-System-Services#45]
With iOS 10.2 , mac address retrieval has been blocked. Is there any way to overcome this?

All the best;

**Comment by Shmoopi** [comment]
"There are no alternative methods supported by Apple, nor there are any special permissions or entitlements you can acquire in order to access MAC address information via the ARP table any more. I cannot comment on other developers’ apps, or how they may have gotten around these restrictions, but given the stance on privacy, any alternate solution you may find right now is likely to fail in the long run." - [https://github.com/mavris/MMLanScan/issues/3](https://github.com/mavris/MMLanScan/issues/3)
