### ISSUE TITLE
How to get deviceSignature in new version

### ISSUE THREAD

**Issue by eggswift** [Shmoopi/iOS-System-Services#50]
How to get deviceSignature in new version? 
Like `[[SystemServices sharedServices] deviceSignature]`

**Comment by Shmoopi** [comment]
Hello @eggswift 

We've removed deviceSignature functionality from the newest version due to increasing limitations in creating a useful signature.  Since most unique attributes of a device are now unobtainable, we cannot create a deviceSignature that would be useful in uniquely identifying a device to nearly any degree of accuracy.  

If you'd like, you can recreate the deviceSignature method from the previous version and attempt to create a better implementation.  

Thank you!
